### PR TITLE
Animated version using matplotlib

### PR DESCRIPTION
**Pull request by dyslexia01**
Hi, I modified your code a bit.

### CODE REVIEW

**Comment by nrxss** [comment]
Wow, alright that is pretty cool. Thanks for the contribution!
Merging now.

**Comment by nrxss** [comment]
Github is bugging a bit. I committed your changes but it tells me there are conflicts? No idea what is going on. 

Your code has been committed in my repository's master branch but the pull request has a branch conflict warning. 

I will try resolving it, in the meantime here is a screenshot of what popped up on my side, in case it happens to know a fix: [imgur link](https://i.imgur.com/JDwj4h1.png) (you may notice that there is no "Resolve conflicts" button top right of the message).

**Comment by dyslexia01** [comment]
Thanks!
Maybe the conflicts has smth to do with the README.md that I changed?

**Comment by nrxss** [comment]
No, there are no actual conflicting files. It is just the Github Web interface bugging with git in the backend or something, I believe.

Your PR was just fine, I just need to figure out how to get it past the conflict warning. Only if you could check whether you can update/sync your branch, in case that fixes it.

I will update you if anything gets working. Again, thank you for your contribution!

**Comment by nrxss** [comment]
Yup that did it, have a nice day!

**Pull request closed without merging**
